### ISSUE TITLE
コードをもっと錆びさせる計画はありますか？

### ISSUE THREAD

**Issue by umaYnit** [yoshitsugu/hariboteos_in_rust#1]
こんにちは、私は現在OSを学んでいて、ネットであなたの記事を見つけました、いい参考になります、ここで感謝します。

そしで、https://os.phil-opp.com/のように、純粋なRust toolchainsを使用するなど、さらに最適化する計画はありますか？
私は今やってみますけど、能力不足で...

**Comment by yoshitsugu** [comment]
@umaYnit ありがとうございます。全然コメントに気づいていませんでした。ゴメンなさい。READMEに書いた通り、一旦これ以上の開発は予定していません。
